openapi: 3.0.0
info:
  title: password-generator
  description: A public API to generate random passwords
  version: 1.0.0
  contact:
    email: anapeksha.mukherjee@gmail.com

servers:
  - url: https://randompassword-generator.herokuapp.com/api/v1
    description: Production server
  - url: http://localhost:4000/api/v1
    description: Development server

paths:
  /generatePWD:
    get:
      summary: returns a random password
      parameters:
        - name: length
          in: query
          required: true
          schema:
            type: number
        - name: characters
          in: query
          required: true
          schema:
            type: string
      responses:
        '200': # status code
          description: returns an object with the password
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
        '400': # status code
          description: error in writing queries
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
